baseURL: https://chiara-lee.github.io/Calenton
languages:
  zh:
    languageCode: zh
    languageName: 中文
    weight: 1
  en:
    languageCode: en
    languageName: English
    weight: 2
title: Caleton Academy of Magic
enableEmoji: true
enableGitInfo: true
Paginate: 3