main:
  - identifier: notes
    name: 笔记
    url: /notes
    weight: 110
  - identifier: thoughts
    name: 思考碎片
    url: /thoughts
    weight: 150
  - identifier: about
    name: 关于
    url: /about
    weight: 200
  - identifier: friends
    name: 友人帐
    url: /friends
    weight: 160

footer:
  - identifier: 
    name: 
    url: 
    weight: 
  - identifier: reference
    name: 引用资料列表
    url: /reference
    weight: 200
  - identifier: categories
    name: 教材索引
    url: /categories
    weight: 200