color: "#4f46e5"
copyright: "Copyright &copy; 2024 Caleton Academy of Magic."
footer:
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
  - title: Important Links
    menu: true
style: blue
recent_posts:
  enable: true
NetlifyCommentForm: 6720c108558e590008ed7242
useNetlifyForComments: true