baseURL:  "$DEPLOY_PRIME_URL"
languages:
  zh:
    languageCode: zh
    languageName: 中文
    weight: 1
  en:
    languageCode: en
    languageName: English
    weight: 2
title: Caleton Academy of Magic
enableEmoji: true
enableGitInfo: true
Paginate: 3

author:
  facebook: "https://facebook.com/example"
  twitter: "https://twitter.com/example"
  email: "contact@example.org"
  name: "Caleton Academy of Magic"
  location: "New York"
  phone: "(999) 999-9999"
  hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"

goldmark:
  renderer:
    unsafe: true
highlight:
  lineNos: true

menu:
  main:
    - identifier: resource
      name: 资源分享
      url: /resource
      weight: 160
    - identifier: blog
      name: 笔记
      url: /blog
      weight: 110
    - identifier: news
      name: 思考碎片
      url: /news
      weight: 150
    - identifier: contact
      name: 关于
      url: /contact
      weight: 200
  footer:
    - identifier: Categories
      name: 目录
      url: /categories
      weight: 150
    - identifier: reference
      name: 引用资料列表
      url: /reference
      weight: 200

params:
  color: "#4f46e5"
  copyright: "Copyright © 2024 Caleton Academy of Magic."
  footer:
    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true
    - title: Important Links
      menu: true
  style: blue
  recent_posts:
    enable: true

related:
  threshold: 10
  includeNewer: true
  indices:
    - name: tags
      weight: 10
    - name: date
      weight: 1
      pattern: 2006

security:
  enableInlineShortcodes: true

taxonomies:
  category: categories
  tag: tags
  series: series
