[build]
  command = "./merge_configs.sh"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.128.0"

[context.deploy-preview]
  command = "./merge_configs.sh"

[context.branch-deploy]
  command = "./merge_configs.sh"


