[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
[build]
  publish = "public"
  command = "npm install && hugo --minify --baseURL $DEPLOY_PRIME_URL"
  ignoreLogs = ["error-remote-getjson"]

[context.production.environment]
  HUGO_VERSION = "0.128.0"
  NODE_VERSION = "20.17.0"
