[build]
  publish = "public"
  command = "hugo  --baseURL $DEPLOY_PRIME_URL"

# 可选：设置生产环境的环境变量
[context.production.environment]
  HUGO_ENV = "production"

[build.environment]
  HUGO_VERSION = "0.128.0"

